name: test

on:
  workflow_dispatch:

jobs:
    runs-on: debian-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.4
      - name: mod-list
        run: |
          sudo bash build-ds3615xs-6.2.4.sh
